import { expect } from 'chai';
import * as chai from 'chai';
import rewire = require('rewire');
import * as sinon from 'sinon';
import * as sinonChai from 'sinon-chai';
import { CliCommand, CmdCli } from '../../src/cli/cmdCli';
import { KubectlAPI } from '../../src/cli/kubectl-api';

chai.use(sinonChai);

suite('Kubectl CLI Command', () => {
  test('should create a proper command string', () => {
    const api = rewire('../../src/cli/kubectl-api');
    // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
    const kubectlCliCommand = api.__get__('kubectlCliCommand');
    const kubectlArguments: string[] = ['version', '--short', '--client'];
    // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-call
    // eslint-disable-next-line
    const commandApi: CliCommand = kubectlCliCommand(kubectlArguments);
    const command: CliCommand = {
      cliArguments: ['version', '--short', '--client'],
      cliCommand: 'kubectl',
    };

    expect(commandApi).to.deep.equal(command);
  });
});

suite('Kubectl API commands that will', () => {
  suite('Apply a file', () => {
    test('should apply a YAML file', () => {
      const command: CliCommand = {
        cliArguments: ['apply', '-f', './path.yaml'],
        cliCommand: 'kubectl',
      };
      const commandAPI = KubectlAPI.applyYAML('./path.yaml', { override: false });
      expect(commandAPI.cliArguments).to.deep.equal(command.cliArguments);
    });
  });

  suite('Print version', () => {
    test('should return command for printing the version of Kubectl', () => {
      const command: CliCommand = {
        cliArguments: ['version', '--short', '--client'],
        cliCommand: 'kubectl',
      };
      expect(KubectlAPI.printVersion().cliArguments).to.deep.equal(command.cliArguments);
    });
  });

  const sandbox = sinon.createSandbox();

  teardown(() => {
    sandbox.restore();
  });

  suite('Get version', () => {
    test('should return the version number', async () => {
      sandbox.stub(CmdCli.getInstance(), 'execute').resolves({ error: undefined, stdout: 'Client Version: v1.18.3' });
      const version = await KubectlAPI.getKubectlVersion('path/to/kubectl');
      expect(version).to.equal('1.18.3');
    });
    test('should return Undefined when the version is not the correct text', async () => {
      sandbox.stub(CmdCli.getInstance(), 'execute').resolves({ error: undefined, stdout: 'not the version text' });
      const version = await KubectlAPI.getKubectlVersion('path/to/kubectl');
      expect(version).to.equal(undefined);
    });
    test('should return Undefined when the version is not returned', async () => {
      sandbox.stub(CmdCli.getInstance(), 'execute').resolves({ error: undefined, stdout: undefined });
      const version = await KubectlAPI.getKubectlVersion('path/to/kubectl');
      expect(version).to.equal(undefined);
    });
    test('should return Undefined for errors', async () => {
      sandbox.stub(CmdCli.getInstance(), 'execute').throws({ error: 'Error generated by a test', stdout: undefined });
      const version = await KubectlAPI.getKubectlVersion('path/to/kubectl');
      expect(version).to.equal(undefined);
    });
  });
});
